.TH PLAYSOUND 1 12/6/2002
.SH NAME
playsound \- play a sound file
.SH SYNOPSIS
.B playsound [sound ...]
.SH DESCRIPTION
playsound is a simple sound player that plays sounds using rplay.
playsound will block until all sounds have been played.  The sound can
be any sound format supported by the rplay server such as mp3, wav,
au, etc.
.SH SEE ALSO
.IR rplay (1)


