.TH RPTP 1 6/29/98
.SH NAME
rptp \- communicate with rplayd using RPTP
.SH SYNOPSIS
.B rptp [options] [command]
.SH DESCRIPTION
rptp is a simple RPTP client that communicates with rplayd using the
RPTP protocol.  Several commands can be issued to control rplayd and
report its status.  See the output of the
.B rptp help
command for a list of available commands.
.OPTIONS
.SH SEE ALSO
.IR rplayd (8),
.IR rplay (1)

